services:
  mysql:
    image: mysql:8
    container_name: toy-store-mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: toy_store
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: server/Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "3001:3001"
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "3000:3000"
    restart: unless-stopped
